name: React Workflow
on:
  push: branches:[main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Setup Node ${{matrix.node-version}}
        uses: action/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: Install Dependencies
        run: yarn install
      - name: Run unit tests
        run: yarn test
